[package]
name = "from-back"
version = "0.1.0"
edition = "2021"
description = "Library for indexing and slicing from the back of a sequence."
repository = "https://github.com/orez-/from-back"

[dependencies]
